const config = {
  entry: [
    "src/app/**/{page,layout,route,error,global-error,loading,not-found,template,default}.{ts,tsx}",
    "desktop/main.ts",
    "desktop/preload.ts",
    "desktop/app-identity.ts",
    "desktop/resources/pi-extensions/*.ts",
    "desktop/**/*.mjs",
    "tools/oxlint/anti-slop/index.ts",
  ],
  project: ["src/**/*.{ts,tsx}", "desktop/**/*.{ts,tsx,mjs}", "tools/**/*.ts"],
  ignore: [".next/**", ".next-dev/**", "node_modules/**"],
  ignoreIssues: {
    "desktop/interfaces.ts": ["types"],
  },
  ignoreDependencies: [
    "@stylexjs/babel-plugin",
    "postcss",
    "tailwindcss",
    "@local-studio/agent-runtime",
    "react-dom",
    "concurrently",
    "depcheck",
    "electron-builder",
    "jscpd",
    "lint-staged",
    "madge",
    "oxlint",
    "oxlint-tsgolint",
    "prettier",
  ],
  ignoreBinaries: [
    "concurrently",
    "next",
    "eslint",
    "oxlint",
    "prettier",
    "depcheck",
    "knip",
    "jscpd",
    "tsc",
    "electron",
    "electron-builder",
    "madge",
    "lint-staged",
  ],
  ignoreExportsUsedInFile: true,
};

export default config;
